### PR TITLE
Update landing page image

### PR DESCRIPTION
**Pull request by dimasciput**
https://github.com/kartoza/clean-cooking-platform/issues/359

### CODE REVIEW

**Comment by dimasciput** [comment]
It will look like this :
image

What do you think @aliciaoberholzer @timlinux

**Comment by aliciaoberholzer** [comment]
We definitely want to have the cooking device in sight. Can you check the
Google photos to see if there are any with better dimensions?

**Comment by dimasciput** [comment]
image

What abou this @aliciaoberholzer ?

**Comment by aliciaoberholzer** [comment]
That looks good to me!

**Pull request merged**
